language: python
sudo: false
notifications:
    email:
        on_success: never
        on_failure: never

python:
    - "3.3"
    - "3.4"
    - "3.5"

install:
    - pip install coveralls

before_script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
    - coverage run --source=Corrector -m unittest discover --start-directory ./Tests/ --verbose

after_success:
    - coveralls