
language: python
sudo: false
notifications:
    email:
        on_success: never
        on_failure: never

python:
    - "3.5"

# command to run tests
script:
    - ls -l
    - cd ./Corrector/Tests
    - python -m unittest