
language: python
sudo: false
notifications:
    email:
        on_success: never
        on_failure: never

python:
    - "3.5"

# command to run tests
script:
    - ll
    - cd ./sub-titles-auto-correct/Corrector/Tests
    - python -m unittest