environment:

  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python310"
    - PYTHON: "C:\\Python311"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39-x64"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install -e ."
  - "%PYTHON%\\python.exe -m pip install pytest"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest tests/ --verbose"
